XMLPath = './sources/source.xml'
RootPath = './sources'
AssetsPath = './assets'
TEMP = '<?xml version="1.0" encoding="UTF-8" ?>'
IncludeIcon = './assets/icons/icon_included.png'
QuestionIcon = './assets/icons/icon_question.png'
ExcludeIcon = './assets/icons/icon_excluded.png'
AppIcon = './assets/icons/icon_app.png'
StyleSheet = './assets/myStyleSheet.qss'
